---
# tasks file for common

- name: update the mapping of hostname and ip address of whole cluster
  lineinfile: dest=/etc/hosts
              line='{{item}}'
  with_items:
          - '115.146.91.128 namenode01'
          - '115.146.89.154 namenode02'
          - '115.146.91.170 resourcemanager01'
          - '115.146.91.179 resourcemanager02'
          - '115.146.91.187 datanode01'
          - '115.146.92.214 datanode02'
          - '115.146.91.198 datanode03'
          - '115.146.92.219 zookeeper01'
          - '115.146.91.20  zookeeper02'
          - '115.146.91.203 zookeeper03'
          - '115.146.87.167 master01'
          - '115.146.87.168 master02'
          - '115.146.95.150 master03'
          - '115.146.95.2   kafka01'
          - '115.146.95.20  kafka02'
          - '115.146.95.200 kafka03'
  become: true


- name: hidding the mapping of 127.0.0.1 to localhost
  lineinfile: dest=/etc/hosts
           regexp='.*127.0.0.1.*novalocal'
           state=absent
  become: true



- name: turn off the firewall
  service: name=firewalld state=stopped
  become: true


- name: create directories
  file: path={{item}} state=directory
  with_items:
          - '{{download_folder}}'
          - '{{app_folder}}'



- name: Download Java from Dropbox
  get_url: url={{java_url}} dest={{download_folder}}



- name: unpackage java into specific folder
  unarchive: src={{java_archive}} dest={{app_folder}} copy=no


- name: add java path to system environment
  lineinfile: dest=/etc/profile
              line='{{item}}'
  with_items:
          - 'export JAVA_HOME={{app_folder}}/jdk1.7.0_80'
          - 'export PATH=$PATH:$JAVA_HOME/bin'
  become: true
  notify: refresh system config file




- name: Download Hadoop from Dropbox
  get_url: url={{hadoop_url}} dest={{download_folder}}


- name: unpackage Hadoop into specific folder
  unarchive: src={{hadoop_archive}} dest={{app_folder}} copy=no


- name: add Hadoop path to system environment
  lineinfile: dest=/etc/profile
              line='{{item}}'
  with_items:
          - 'export HADOOP_HOME={{app_folder}}/hadoop-2.4.1'
          - 'export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin'
  become: true
  notify: refresh system config file


- name: create hadoop working directory
  file: path='{{app_folder}}/hadoop-2.4.1/tmp/' state=directory



- name: modify configuration file
  copy: src='{{item.src}}' dest='{{item.dest}}'
  with_items:
    - {src: hadoop-env.sh, dest: '{{app_folder}}/hadoop-2.4.1/etc/hadoop/hadoop-env.sh' }
    - {src: core-site.xml, dest: '{{app_folder}}/hadoop-2.4.1/etc/hadoop/core-site.xml' }
    - {src: hdfs-site.xml, dest: '{{app_folder}}/hadoop-2.4.1/etc/hadoop/hdfs-site.xml' }
    - {src: mapred-site.xml, dest: '{{app_folder}}/hadoop-2.4.1/etc/hadoop/mapred-site.xml' }
    - {src: yarn-site.xml, dest: '{{app_folder}}/hadoop-2.4.1/etc/hadoop/yarn-site.xml' }
    - {src: slaves, dest: '{{app_folder}}/hadoop-2.4.1/etc/hadoop/slaves' }


- name: replace native library to 64 bits
  copy: src=/Users/charlie/Desktop/ENGR90033/Ansible/roles/common/lib/  dest=/home/ec2-user/apps/hadoop-2.4.1/lib/
